CC = g++

#CFLAGS = -static -D DEBUG -g

CFLAGS= -static -Werror

INCLUDES = -luv -lcryptopp -largon2  -lpthread -lntru 

LIBS = -L./lib/cryptopp/ -L./lib/argon2/ -L./lib/libuv/ -L./lib/libntru/

TARGET = coherence

all: $(TARGET)

$(TARGET): $(TARGET).c
	$(CC) $(CFLAGS) -o $(TARGET) $(TARGET).c $(INCLUDES) $(LIBS) 


